# Generated by Django 4.1.7 on 2023-04-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=1000, unique=True)),
                ('admin', models.BooleanField(verbose_name='Adminsitrador')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
