# Generated by Django 4.1.7 on 2023-04-01 19:48

from django.db import migrations
from chess_web import settings
from django.contrib.auth.hashers import make_password

def usuario_root(apps, schema_editor):
    Usuario = apps.get_model(settings.AUTH_USER_MODEL)
    Usuario.objects.create(
        email='root@ifmg.br',
        password=make_password('ifchess'),
        nome='IFChess Root',
        admin=True
    )



class Migration(migrations.Migration):

    dependencies = [
        ('chess_web', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(usuario_root)
    ]
