# Generated by Django 4.1.7 on 2023-04-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_web', '0002_usuario_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='Adminsitrador'),
        ),
    ]
