# Generated by Django 4.1.5 on 2023-04-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_web', '0003_alter_usuario_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=500)),
                ('data', models.DateField()),
                ('organizacao', models.CharField(max_length=100)),
            ],
        ),
    ]
