# Generated by Django 4.1.5 on 2023-04-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('chess_web', '0004_torneios'),
    ]

    operations = [
        migrations.CreateModel(
            name='perfil_cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1000)),
                ('idade', models.TextField(max_length=3)),
                ('email', models.EmailField(max_length=1000, unique=True)),
                ('senha', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=1000)),
                ('estado', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='perfil_usuario',
        ),
    ]
