# Generated by Django 4.1.5 on 2023-04-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('chess_web', '0005_perfil_cadastro_rename_usuario_perfil_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='perfil_usuario',
            new_name='Usuario',
        ),
        migrations.DeleteModel(
            name='perfil_cadastro',
        ),
    ]
