# Generated by Django 4.2 on 2023-04-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_web', '0006_candidatos_rename_perfil_usuario_usuario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='candidatos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='descricao',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='facebook',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='instagram',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='twitter',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
