# Generated by Django 4.2 on 2023-04-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_web', '0008_alter_torneios_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneios',
            name='premio_primeiro',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='torneios',
            name='premio_segundo',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='torneios',
            name='premio_terceiro',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
