# Generated by Django 4.2.1 on 2023-05-15 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess_web', '0010_partida_alter_usuario_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='Torneios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chess_web.torneios'),
        ),
    ]
