# Generated by Django 4.1.7 on 2023-06-07 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess_web', '0011_partida_torneios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='Torneios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_web.torneios'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='torneio',
            field=models.CharField(max_length=1000),
        ),
    ]
